### ISSUE TITLE
Can't get install using npm

### ISSUE THREAD

**Issue by mygituser12** [KomodoPlatform/Agama#105]
Hey , this is totally new for me,
i have tried the steps given in read.me file. but i am getting error at step 6. 
like ,
3) git checkout dev && git pull origin dev
4) npm install && npm install webpack
5) ./binary_artifacts.sh
6) npm start in project root folder

```
ubuntu@ip-172-31-25-25:~/agama$ npm start

> agama-app@0.2.42 start /home/ubuntu/agama
> electron .


npm ERR! Linux 3.13.0-149-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.14.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! agama-app@0.2.42 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the agama-app@0.2.42 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.

```
please help me with this error to figured it out.

**Comment by pbca26** [comment]
this is not a helpful output
are there any details you see?
have you ran npm install in root dir?

**Comment by mygituser12** [comment]
Hi, thanks for replying.
previous issue was solved by upgrading node version to v8.
now i am getting another issue while running `` npm start  `` in root directory.
when i run ``npm start`` the blank window is opening and following message is displaying in terminal
```
> agama-app@0.2.42 start /var/www/html/agama
> electron .

proxy server 94.130.225.86:80
Option origins is not valid. Please refer to the README.
```
please help me with this.
thanks.

**Comment by pbca26** [comment]
since agama is a two piece app you need to run gui build as well
open another terminal window
cd to agama's folder
type cd gui
git pull -b dev https://github.com/komodoplatform/easydex-gui
cd EasyDEX-GUI/react
npm install
npm run
restart main app

**Comment by mygituser12** [comment]
Hello @pbca26  , 
I did the same and the following is output .
root directory ``npm start``
following are the screenshots of ``root`` directory 

![agama-root](https://user-images.githubusercontent.com/42665380/46518827-d55a1b00-c893-11e8-9c56-8b6a5c73bb60.png)


and ``/gui/EasyDEX-GUI/react``

![gui-react](https://user-images.githubusercontent.com/42665380/46518624-c1fa8000-c892-11e8-938c-56195db9259b.png)

as you can see that there is js error in root directory pop window.
so that error is normal or else that's a reason for not working the app?

i hope you are getting my problem and do something for that.

Thanks.

**Comment by pbca26** [comment]
can you post contents of your .agama/config.json?

**Comment by mygituser12** [comment]
here is my .agama/config.json
```json
{
  "host": "127.0.0.1",
  "agamaPort": 17777,
  "maxDescriptors": {
    "darwin": 90000,
    "linux": 1000000
  },
  "dev": false,
  "debug": false,
  "roundValues": false,
  "experimentalFeatures": false,
  "dataDir": "",
  "dex": {
    "walletUnlockTimeout": 3600
  },
  "cliStopTimeout": 1000,
  "failedRPCAttemptsThreshold": 10,
  "stopNativeDaemonsOnQuit": true,
  "lang": "EN",
  "rpc2cli": false,
  "fiatRates": false,
  "loadCoinsFromStorage": false,
  "requirePinToConfirmTx": false,
  "spv": {
    "maxVinParseLimit": 120,
    "cache": false,
    "proxy": false,
    "socketTimeout": 10000,
    "customServers": false,
    "syncServerListFromKv": false,
    "allowCustomFees": false,
    "listtransactionsMaxLength": 10,
    "csvListtransactionsMaxLength": 400
  },
  "defaultFiatCurrency": "usd",
  "native": {
    "rpc2cli": false,
    "cliStopTimeout": 1000,
    "failedRPCAttemptsThreshold": 10,
    "stopNativeDaemonsOnQuit": true,
    "dataDir": "",
    "listtransactionsMaxLength": 300,
    "csvListtransactionsMaxLength": 1000,
    "zlistreceivedbyaddress": false,
    "zgetoperationresult": false
  },
  "pubkey": "",
  "daemonOutput": false
}
```

**Comment by pbca26** [comment]
config looks good
please try to run npm start in agama root again and see if it will fix the issue

**Comment by Lucioric2000** [comment]
I solved if by reinstalling Agama again, including re-clone, running the instructions of the Agama installer from the directory where the agama dir would be a subdirectory. Because if you run the install.sh from the location in the clone, you end up with an agama subdirectory under your clone "Agama" dir, and in such mode you after build end up with the files in 3 different locations.

**Comment by jdmarlow86** [comment]
Is this issue resolved?

**Comment by Lucioric2000** [comment]
Yes, it is resolved.
