### ISSUE TITLE
Cannot logout (soft or complete) from lite mode connection error screen

### ISSUE THREAD

**Issue by imylomylo** [KomodoPlatform/Agama#149]
Cannot logout from lite mode connection error screen in transaction view.   (when it says, go to settings and choose a different server)

Will provide gif in future.

**Comment by pbca26** [comment]
i can't seem to reproduce it
do you have any specific steps to reproduce
better if you can grab a video

**Comment by himu007** [comment]
@imylomylo Please create a new issue if you experience this in the future and please add a short vid or gif. I'm closing this issue now as I couldn't also reproduce this on my end.
