### ISSUE TITLE
Hush: Inaccurate Block Confirmation Counts

### ISSUE THREAD

**Issue by matthewjamesr** [KomodoPlatform/Agama#15]
## Issue

Confirmation counts always remain at `0`.

Edit 1: Seems confirmations have updated, although at a significant delay. Perhaps a polling issue.

**Comment by pbca26** [comment]
yes, electrum server has higher latency compared to native
it's not instant
for example btg sometimes takes about 10 min to get a 1 conf

**Comment by pbca26** [comment]
would be really helpful if you attach a screenshot next time just for a reference

**Comment by matthewjamesr** [comment]
Hey,

Thanks for the explanation on electrum latency. Leaving this open pending a PR for additional Hush electrums.
