### ISSUE TITLE
Cannot copy wif key, cannot send arrr

### ISSUE THREAD

**Issue by nikolayganovski1** [KomodoPlatform/Agama#181]
I'm using PIRATE chain, my wallet is synced at 98.5%, but keeps throwing these errors: 
<img width="168" alt="fdfdfq1" src="https://user-images.githubusercontent.com/11571028/51015642-b0053900-1575-11e9-9a82-77526c8ae5f1.png">

And when try to copy wif key:
<img width="165" alt="qweqwewe2" src="https://user-images.githubusercontent.com/11571028/51015693-e0e56e00-1575-11e9-8de5-956579e3bf9d.png">
i am now worried if my hard drive blocks, without the wif key exported, all my funds will burn away.

**Comment by himu007** [comment]
**Always backup your `wallet.dat`. As long as you have that, you can use it in any computer and exporting WIF is not necessary. No need to be scared.**
You can ignore those warnings. Best thing to do is, stop all programs, restart Agama wait for sync to be 100%.
