### ISSUE TITLE
Developer instruction failing

### ISSUE THREAD

**Issue by sawlysawly** [KomodoPlatform/Agama#185]
Hi

I follow all developer instructions steps in readme but app screen is blank.

I have front end runnings:

![screenshot_2019-01-15_10-34-29](https://user-images.githubusercontent.com/46623667/51176200-3abaa080-18b4-11e9-97cc-9dba56b45c84.png)

But I cant completes last bits of electron intructions (change dev and debug options and restart) because elctron window is blank:

![screenshot_2019-01-15_10-23-26](https://user-images.githubusercontent.com/46623667/51176299-76556a80-18b4-11e9-8cbd-2517ca3b7454.png)

I gets the console electron errors:

```
Not allowed to load local resource: file:///home/user/dev/Agama/gui/EasyDEX-GUI/react/build/index.html
```

And in the terminals:

```
$ npm start                                                                        

> Agama@0.3.3 start /home/user/dev/Agama
> cross-env NODE_ENV=development electron .

proxy server 94.130.98.74:80
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
Option origins is not valid. Please refer to the README.
user@host:~/dev/Agama$
user@host:~/dev/Agama$ npm start

> Agama@0.3.3 start /home/user/dev/Agama
> cross-env NODE_ENV=development electron .

proxy server 94.130.225.86:80
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
Option origins is not valid. Please refer to the README.
```

Did I make mistakes? Any advices or reccomendations?

**Comment by sawlysawly** [comment]
I resolved the problems, seem like developer instruction is incorrects.

I need to manually edit `~/.agama/config.json` because of no dev option in GUI to toggle.

@pbca26 I think the change should be made to either add dev toggle to GUI or update readme to explain to edit the JSON file. What do you want? Maybe can I help to do the fix if you say what to change?

**Comment by pbca26** [comment]
i pushed updated readme to dev branch
you can also run it via devmode param now

**Comment by sawlysawly** [comment]
Thanks for fix. seems issue is fixed now I can close this issue.
