### ISSUE TITLE
Enhancement: Native mode progress bar and information text isn't readable

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/Agama#203]
I can't see text on synchronization progress bar (tried on the little screen of Mac Air and Full HD display as well)
Text in the box above not easy readable as well (blue on blue).
Screenshot attached.
I propose to "play with colors" to make text clearly visible (I'm bad in design stuff so sorry for abstract proposal).
![screenshot at jan 27 00-21-17](https://user-images.githubusercontent.com/24797699/51790623-69951880-21ca-11e9-8164-427400de1cbe.png)

**Comment by sawlysawly** [comment]
i will like to work on fixing this

**Comment by sawlysawly** [comment]
@tonymorony what os did you used?

i can see ok on my testing on linux and mac

![sync](https://user-images.githubusercontent.com/46623667/52461476-21c9a600-2b67-11e9-856a-f4d4ffee706a.png)

not as bad likes in your screenshot but I can agree it could be better with different color

**Comment by sawlysawly** [comment]
i thinking the progress bar text look much easy to read with dark text color 

![sync dark text](https://user-images.githubusercontent.com/46623667/52461856-c4ceef80-2b68-11e9-86f7-2fa79ef2e61a.png)


@pbca26 @tonymorony @himu007 what are you guys think?

**Comment by tonymorony** [comment]
It was fixed in one of the latest releases

**Comment by tonymorony** [comment]
@sawlysawly imo black font looks really clear here.
I guess you can PR black font for this text if @pbca26 @himu007 agree with this change

**Comment by sawlysawly** [comment]
@pbca26 @himu007 will wait to hearing from you about this

i will be happy to submit a PR if you like

**Comment by sawlysawly** [comment]
i didnt hearing anything for some time so i made the PR https://github.com/KomodoPlatform/EasyDEX-GUI/pull/124

i think its looking better but up to your decision

**Comment by sawlysawly** [comment]
@pbca26 @tonymorony i dont have the permissions to close this but i m thinking this issue can be closed now

**Comment by tonymorony** [comment]
Thank you @sawlysawly ! Closed 👍
