### ISSUE TITLE
Show fiat value

### ISSUE THREAD

**Issue by sawlysawly** [KomodoPlatform/Agama#219]
i think it would be nice feature to show fiat value on dashboard

i have hacked in a quack version of whats it can look like

![agama-fiat](https://user-images.githubusercontent.com/46623667/52513355-41fa7300-2c02-11e9-8190-c5954344e8a3.png)

i can submits a PR if you like this change

**Comment by pbca26** [comment]
we already have fiat values
just toggle this option in settings

**Comment by sawlysawly** [comment]
oh aplogies i did not see this option
