### ISSUE TITLE
Native notification

### ISSUE THREAD

**Issue by sawlysawly** [KomodoPlatform/Agama#225]
i just have an idea

i think it would be good to have the option to toggle to enable native notification instead of bootstrap notification inside webview

so mac notofication on mac gnome notification on ubuntu

if you interest to have this i m able to do the PR

**Comment by pbca26** [comment]
sure, sounds an interesting idea

**Comment by sawlysawly** [comment]
this is good news!

i will working about putting PR together and let you know when to review

**Comment by sawlysawly** [comment]
completes with this prs
https://github.com/KomodoPlatform/Agama/pull/229
https://github.com/KomodoPlatform/EasyDEX-GUI/pull/126
