### ISSUE TITLE
Transaction history wrongly displayed

### ISSUE THREAD

**Issue by passcombo** [KomodoPlatform/Agama#26]
hey guys, using multipl coins in SPV mode sometiems is a bit confusing - different coins panels are mixing, for example when I click t o view the other coin - it shows the balance of it, but the transactions from the previous one

also can show 2 addresses - current wallet  + the other one from confused transactions
kind of refresh bug or cache bug, not very big but someone can confuse accounts and send money from 1 coin to the other one (as 2 diff addresses displayed on 1 panel! destination address in transaction history != wallet address on top )
win 10 wallet Agama .27a

example:
transfering 10 Hush is shown also when displaying BCH SPV. In that case I can see 1 address of BCH + 1 address of Hush in BCH transaction history.
In my case BCH was added just after Hush on the coins SPV list.
After few minutes BCH shows:
Connection error!
Trying to switch to another server...
How to switch manually:
Go to "Settings", select "SPV Server List" tab, choose new server and click "OK".

**Comment by passcombo** [comment]
Yes, and sometimes Hush wallet displays me KMD transaction history in place of Hush transaction history. Seems SPV soemtiems random :P

**Comment by jdmarlow86** [comment]
No longer an issue, closing
