### ISSUE TITLE
Agama wallet hacked

### ISSUE THREAD

**Issue by Vaklam** [KomodoPlatform/Agama#261]
My agama wallet was hacked no notification, no warning, all my KMD withdrawn, any recourse or am I screwed?

**Comment by gcharang** [comment]
Hello, please use the contact form at https://komodoplatform.com/en/contact.html to describe your issue and send your KMD address.

**Comment by GarettBill** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me recover all my funds,message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by smk762** [comment]
> Same thing happened to me but thanks to REDACTED who helped me recover all my funds,message him on telegram his telegram username is REDACTED

Reported. Do not seek support from this person, they are not authorised and likely trying to scam you.
