### ISSUE TITLE
Agama Linux wallet does not shut down with Komodo in native mode

### ISSUE THREAD

**Issue by finddabug** [KomodoPlatform/Agama#33]
When running the Agama wallet for Linux (0.2.0.27c-beta) in native mode with only the Komodo as the only coin in the wallet; the wallet does not shut down when you press the x in the corner. The wallet main window closes and the "shut down window" pops up but never goes away even after several hours. Only killing the process works

**Comment by jdmarlow86** [comment]
Closing issue
