### ISSUE TITLE
please remove empty space in Lite mode.

### ISSUE THREAD

**Issue by goldenman-kmd** [KomodoPlatform/Agama#41]
OS : windows 10
Ver : 28b

description : 

please remove empty space beside total balance in Lite mode.
I think that is for Z-balance in native mode, but no need that in lite mode .

![image](https://user-images.githubusercontent.com/33863358/36850044-07ee785e-1da9-11e8-93ac-3c49df6f59b3.png)

**Comment by jdmarlow86** [comment]
Issue is corrected, closing
