### ISSUE TITLE
Can't import zwif

### ISSUE THREAD

**Issue by ptyx11** [KomodoPlatform/Agama#47]
https://screencast-o-matic.com/watch/cFe6ryDFbY

**Comment by patchkez** [comment]
Also please fix the typo in error flash message:
![screenshot-20180311 121851](https://user-images.githubusercontent.com/11808967/37256326-47c65a3e-2559-11e8-98dd-88b2c0ad8dea.png)

**Comment by pbca26** [comment]
fixed in v2.31
