### ISSUE TITLE
Not seeing some receiving addresses after reinstalling agama.

### ISSUE THREAD

**Issue by zzProphetzz** [KomodoPlatform/Agama#61]
Hi,
If anyone can help me.

For some reason, I am not seeing some addresses after reinstalling
agama on my laptop. I have imported the key that was generated
when I first installed it and all.

Now I am seeing only one and I had kmd on the other and not
able to see it.

Thanks for your help.

**Comment by ip-config** [comment]
i can fix it

**Comment by zzProphetzz** [comment]
Hi,

How can it be fixed?

Thanks!

**Comment by jdmarlow86** [comment]
Closing issue, will reopen if needed
