### ISSUE TITLE
Agama.exe - Application Error

### ISSUE THREAD

**Issue by digitalwav** [KomodoPlatform/Agama#80]
Received following error after install and first run on a Windows 10 x64 system. Using latest version from GitHub "AgamaApp-0.2.38-beta-windows-installer".

Agama.exe - Application Error
The application was unable to start correctly (0xc000007b). Click OK to close the application.

![image](https://user-images.githubusercontent.com/39857870/40877130-a8241de0-6630-11e8-954b-a38962a4bfe4.png)

**Comment by pbca26** [comment]
have you tried to use compatibility in file properties? also try to run as admin

**Comment by digitalwav** [comment]
Tried running as admin and running the compatibility
troubleshooting wizard. No luck. Still not working.

**Comment by pbca26** [comment]
please try v0.2.40 perhaps that will fix the issue

**Comment by digitalwav** [comment]
Weird. I can't find any of the newer (2018) releases of Agama today on Github. See screenshot...

I used the newest version from "https://komodoplatform.com/komodo-wallets/" which is "AgamaApp-0.2.39-beta-windows-installer". I had the exact same issue and error message after installing. Will test out version 0.2.40 once it's available.

![github releases](https://user-images.githubusercontent.com/39857870/41863053-8665e08a-785a-11e8-97f1-41bedda289ca.png)

**Comment by digitalwav** [comment]
Just tried version "AgamaApp-0.2.41-beta-windows-installer". It installs without issue but after trying to start it I get the same error. Attached is a simple debug of the application runtime and exit error code.

![image](https://user-images.githubusercontent.com/39857870/42732252-c74a8420-87d2-11e8-9929-eb3f3a076c61.png)

**Comment by jdmarlow86** [comment]
Closing, issue is resolved
