### ISSUE TITLE
transaction link to blockcypher for dash broken

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/Agama#83]
In TxID screen, onclick link from "open transaction in DASH Explorer" = https://live.blockcypher.com/dash8f0ac74a415d3df0f82979970c76bf99f7421e5f63867fd52e55ccd83d3fa648/

should be - https://live.blockcypher.com/dash `/tx/` 0dc1da033a96b5addcb2459cdb855ddf8a4a79a44317a80acdf6d77d93d8c647/

**Comment by pbca26** [comment]
thanks, will be fixed in the next release
