### ISSUE TITLE
Win 7 native sync

### ISSUE THREAD

**Issue by jdmarlow86** [KomodoPlatform/Agama#91]
Reported by a user.

After a full native sync -> then shutdown -> then reopen -> app starts download again

Version: 41a
OS: win 7
Errors: none

**Comment by pbca26** [comment]
1) "CLI stop timeout" option in settings
2) there's a vertical ellipsis icon at each coin tile on the left side. If you click it a dropdown will appear and you can stop a daemon

**Comment by ThorthChariot** [comment]
ok thanks :)  i'll try :)  if still i have issue  i'll say

**Comment by ThorthChariot** [comment]
ok... i put all those info :)  but again :)  when i open my wallet... start download again the chain ... :|  every single time

**Comment by pbca26** [comment]
do you have a regular hdd or ssd?

**Comment by jdmarlow86** [comment]
Closing for now, will reopen if reported again
